import json
import os
from .database import SessionLocal
from .models import DataItem, MapPoint, Region, Stat

MOCK_DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mock_data.json")


def seed_all(db=None):
    """Seed database from mock_data.json generated by export_mock_data.mjs."""
    if db is None:
        db = SessionLocal()

    try:
        with open(MOCK_DATA_PATH, "r", encoding="utf-8") as f:
            all_data = json.load(f)
    except FileNotFoundError:
        print(f"mock_data.json not found at {MOCK_DATA_PATH}, skipping seed")
        return

    for module, items in all_data.items():
        for item_id, item in items.items():
            # Insert DataItem
            map_data = item.get("mapData", {})
            chart_data = item.get("chartData", {})

            data_item = DataItem(
                id=item_id,
                module=module,
                name=item.get("name", ""),
                description=item.get("description", ""),
                map_type=map_data.get("type", "scatter"),
                chart_type=chart_data.get("type", "bar"),
                chart_title=chart_data.get("title", ""),
                chart_x_field=chart_data.get("xField", "district"),
                chart_y_field=chart_data.get("yField", "value"),
                chart_unit=chart_data.get("unit", ""),
            )
            db.add(data_item)

            # Insert MapPoints
            for pt in map_data.get("points", []):
                extra = {}
                for key in ("category", "type", "history", "era", "area", "line", "scale", "peak"):
                    if key in pt and pt[key] is not None:
                        extra[key] = pt[key]

                point = MapPoint(
                    data_item_id=item_id,
                    lat=pt["lat"],
                    lng=pt["lng"],
                    value=pt["value"],
                    name=pt["name"],
                    district=pt["district"],
                    extra_json=json.dumps(extra, ensure_ascii=False) if extra else "{}",
                )
                db.add(point)

            # Insert Regions
            for i, reg in enumerate(map_data.get("regions", [])):
                region = Region(
                    data_item_id=item_id,
                    district=reg["district"],
                    value=reg["value"],
                )
                db.add(region)

            # Insert Stats
            for i, stat in enumerate(item.get("stats", [])):
                s = Stat(
                    data_item_id=item_id,
                    label=stat["label"],
                    value=stat["value"],
                    trend=stat.get("trend"),
                    sort_order=i,
                )
                db.add(s)

    db.commit()
    print(f"Seeded database with data for modules: {list(all_data.keys())}")


if __name__ == "__main__":
    db = SessionLocal()
    try:
        seed_all(db)
    finally:
        db.close()
